version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 12.11.5, < 12.12"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.3, < 12.13"
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.34
    - 14.14.36
    - 14.14.39
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 8.0.15
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.4
    - 3.6.6
    - 3.6.8
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.1
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: music-metadata
    versions:
    - 7.6.7
    - 7.7.0
