version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "@types/jasmine"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "music-metadata"
      versions: [ ">=8.x" ]
